name: 'Check pull request title'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  checks:
    uses: etn-utilities/smp-devsecops-workflows/.github/workflows/pull-requests-check-pr-title.yml@eaton/smp/main
    secrets: inherit
